version: '3.3'

services:
  cms:
    build:
      args:
        - SANITY_STUDIO_PROJECT_ID=${SANITY_STUDIO_PROJECT_ID:?error}
        - SANITY_STUDIO_DATASET=${SANITY_STUDIO_DATASET:?error}
        - SANITY_API_VERSION=${SANITY_API_VERSION:?error}
        - SANITY_STUDIO_PREVIEW_URL=${SANITY_STUDIO_PREVIEW_URL:?error}
      context: .
      dockerfile: ./apps/cms/Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - ".env"
    restart: always

  web:
    build:
      args:
        - SANITY_STUDIO_PROJECT_ID=${SANITY_STUDIO_PROJECT_ID:?error}
        - SANITY_STUDIO_DATASET=${SANITY_STUDIO_DATASET:?error}
        - SANITY_API_VERSION=${SANITY_API_VERSION:?error}
        - YANDEX_MAPS_API_KEY=${YANDEX_MAPS_API_KEY:?error}
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    restart: always