export const DefaultCurriculumConstants = {
    ACADEMIC_HOURS_PER_HALF_YEAR: 72,

    SCHEDULE_DAYS_PER_WEEK: 2,
    SCHEDULE_LESSON_DURATION_IN_ACADEMIC_HOURS: 2,

    STUDENTS_COUNT_IN_GROUP: 12,
    STUDENTS_MIN_AGE: 12,
    STUDENTS_MAX_AGE: 18,
} as const
