export const API_VERSION = process.env.SANITY_API_VERSION

export const CURRICULUM_LEVEL = {
    'INTRODUCTORY': 1,
    'ADVANCED': 2,
    'PROJECT': 3,
} as const

export const DEFAULT_CURRICULUM_HALF_YEAR_HOURS = 72

export const DEFAULT_CURRICULUM_MIN_AGE = 12
export const DEFAULT_CURRICULUM_MAX_AGE = 18

export const MAX_CURRICULUM_AGE = 18

export const DEFAULT_CURRICULUM_SCHEDULE_DAYS_PER_WEEK = 2
export const DEFAULT_CURRICULUM_SCHEDULE_LESSON_DURATION = 2

export const DEFAULT_CURRICULUM_STUDENTS_COUNT_IN_GROUP = 12
